name: Array Test

inputs:
  array:
    description: "Array value"
    required: true

runs:
  using: composite
  steps:
    # - uses: actions/cache@v3
    #   with:
    #     path: |
    #       **/node_modules
    #     key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Debug
      run: |
        arr=$'${{ inputs.array }}'
        y=(${arr//$'\n'/ })
        for i in "${y[@]}"
        dir=$(pwd)
        do
          echo "==============="
          cd "${dir}/${i}"
          ls -al
          echo "==============="
        done
      shell: bash
