name: Array Test

inputs:
  array:
    description: "Array value"
    required: true

runs:
  using: composite
  steps:
    - name: Debug
      run: |
        arr=$'${{ inputs.array }}'
        y=(${arr//$'\n'/ })
        for i in "${y[@]}"
        do
          echo "==============="
          echo "$i"
          echo "==============="
        done
      shell: bash
