name: Array Test

inputs:
  array:
    description: "Array value"
    required: true

runs:
  using: composite
  steps:
    # - uses: actions/cache@v3
    #   with:
    #     path: |
    #       **/node_modules
    #     key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: Debug
      run: |
        arraystring=$'${{ inputs.array }}'
        array=(${arraystring//$'\n'/ })
        dir="$(pwd)"

        for arr in "${array[@]}"
        do
            echo "==============="
            path="${dir}/${arr}"
            if [ ! -d "${path}" ]; then
                continue
            fi
            
            cd "${path}"
            ls -al
            echo "==============="
        done
      shell: bash
