name: Array Test

inputs:
  array:
    description: "Array value"
    required: true

runs:
  using: composite
  steps:
    - name: Debug
      run: |
        arr=$${{ inputs.array }}
        for i in "${arr[@]}"
        do
          echo "$i"
        done
      shell: bash
