name: Array Test

on: push

jobs:
  wellknown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/array-test
        with:
          array: value, 3333, 23232323, 111111
      - uses: ./.github/actions/array-test
        with:
          array: |
            value
            3333
            23232323
            111111
