name: Array Test

on: push

jobs:
  arrayval:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/array-test
        with:
          array: docker helm static
      - uses: ./.github/actions/array-test
        with:
          array: |
            docker:minify-test
            helm
            static
