name: Close Action

on: workflow_dispatch

jobs:
  tag-changelog:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@main

    - name: sleep
      run: |
        sleep 120
