name: Close Action

on: push

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tag-changelog:
    runs-on: ubuntu-22.04
    timeout-minutes: 10
    steps:
    - name: sleep
      run: |
        sleep 121
