name: Main

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
            mkdir -p myfolder
            echo ${{ github.sha }} > myfolder/Release.txt
            echo "release" > myfolder/Release2.txt
            tar -czvf myfolder.tar.gz -C myfolder .

      - name: Release
        uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: myfolder.tar.gz
