name: Fetch Json

on:
  workflow_dispatch

jobs:
  terraform:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check if Action Runs Already
        id: action
        run: |
          releaseDate=$(date '+%B-%-d-%Y' | tr '[:upper:]' '[:lower:]')
          echo $releaseDate
          workflow=$(echo ".github/workflows/terraform-apply.yml" | cut -d/ -f3)
          workflow=$(echo "${{ github.workflow }}" | cut -d/ -f3)
          echo "https://api.github.com/repos/${{github.repository.full_name}}/actions/workflows/$workflow/runs?status=in_progress"
          runs=$(curl -H "Accept: application/vnd.github.groot-preview+json" "https://api.github.com/repos/${{github.repository.full_name}}/actions/workflows/$workflow/runs?status=in_progress")
          count=$(jq ".[0].total_count" <<< "$runs")
          echo "$count"
          echo "::set-output name=count::$count"

      - name: Fetch json1
        id: items
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://raw.githubusercontent.com/junminahn/testteste/main/static/sample-ids.json"
          method: "GET"
        continue-on-error: true

      - name: Show Response1
        id: res1
        run: |
          count=$(jq length <<< ${{ steps.items.outputs.response }})
          echo "::set-output name=count::$count"

      - name: Run if has more than zero
        if: steps.res1.outputs.count != '0'
        run: echo ${{ steps.res1.outputs.count }}

      - name: Fetch json2
        id: empty
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://raw.githubusercontent.com/junminahn/testteste/main/static/empty-ids.json"
          method: "GET"
        continue-on-error: true

      - name: Show Response2
        id: res2
        run: |
          count=$(jq length <<< ${{ steps.empty.outputs.response }})
          echo "::set-output name=count::$count"

      - name: Run if has more than zero
        if: steps.res2.outputs.count != '0'
        run: echo ${{ steps.res2.outputs.count }}
