name: Fetch Json

on:
  workflow_dispatch

jobs:
  terraform:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Fetch json
        id: items
        uses: fjogeleit/http-request-action@master
        with:
          url: "https://raw.githubusercontent.com/junminahn/testteste/main/static/sample-ids.json"
          method: "GET"
        continue-on-error: true

      - name: Show Response
        run: |
          number=$(jq length <<< ${{ steps.items.outputs.response }})
          echo "$number"
