name: Issue

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  iss:  
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      
      # NPM PACKAGES
      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: Install Yarn dependencies in root
        run: yarn

      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const script = require('./github-script.js')
            console.log(script({github, context}))
