name: Issue

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  iss:  
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - uses: actions/github-script@v4
        with:
          script: |
            const script = require('./github-script.js')
            console.log(script({github, context}))
