name: Keycloak Well-Known

on:
  push

jobs:
  wellknown:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: wellknown
        id: wellknown
        uses: ./.github/actions/wellknown
        with:
          discovery-url: https://dev.loginasdfproxy.gov.bc.ca/auth/realms/standard/.well-known/openid-configuratiasdfon
        continue-on-error: true

      - run: |
          echo ${{ steps.wellknown.outputs.config }}
