name: "PR CI Test"
on:
  pull_request:
    types: [opened, edited, labeled]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = JSON.stringify(${{ github.event }}, null, 2);
            console.log(output);
