name: "PR CI Test"

on:
  pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: hmarr/debug-action@v2

    - name: Get PR
      id: pr
      run: |
        pr=$(curl -H "Accept: application/vnd.github.groot-preview+json" ${{github.event.pull_request._links.issue.href}})
        aaa=$(jq -c '.' <<< "$pr")
        echo $aaa
        echo "::set-output name=pr::$aaa"

    - name: Get PR2
      id: pr2
      run: |
        echo ${{ fromJSON(steps.pr.outputs.pr) }}

    - name: Get PR3
      if: contains(steps.pr.outputs.pr.labels.*.name, 'documentation')
      run: |
        echo step3