name: Tag Environment

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=${GITHUB_REF_NAME#v}" >> $GITHUB_ENV

      - name: Display IMAGE_TAG
        run: echo $IMAGE_TAG
