name: Create Tag

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: Tag Version (incl. prefix; e.g. v1.2.3)
        required: true
      message:
        type: string
        description: Tag Message (e.g. Story Number)
        required: true

jobs:
  tag-changelog:
    runs-on: ubuntu-22.04

    steps:
    - name: Fail on tags
      run: exit 1
      if: ${{ !startsWith(github.ref, 'refs/heads/') }}

    - uses: hmarr/debug-action@a701ed95a46e6f2fb0df25e1a558c16356fae35a
    - uses: actions/checkout@96f53100ba2a5449eb71d2e6604bbcd94b9449b5
      with:
        ssh-key: ${{ secrets.SSH_KEY }}
        fetch-depth: 0 # fetch all history for all branches and tags

    - name: Create a tag
      run: |
        git config user.name "$GITHUB_ACTOR"
        git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git config commit.gpgsign false

        git tag -a ${{ github.event.inputs.tag }} -m "${{ github.event.inputs.message }}"
        git push origin ${{ github.event.inputs.tag }}
