name: Keycloak Well-Known

on:
  push

jobs:
  wellknown:
    runs-on: ubuntu-latest
    steps:
    - name: Fetch Well-Known
      id: fetch
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://dev.loginproxy.gov.bc.ca/auth/realms/standard/.well-known/openid-configuration'
    - name: Show Response
      run: |
        echo ${{ steps.fetch.outputs.response }}
        echo ${{ steps.fetch.outputs.headers }}
        echo ${{ fromJson(steps.fetch.outputs.response).jwks_uri }}
